- name: Create volume for nextcloud container
  file:
    path: /srv/nextcloud
    state: directory
    recurse: yes
  become: yes

- name: Create database user for Nextcloud
  postgresql_user:
    login_host: "{{ postgresql_ip }}"
    login_user: root
    login_password: "{{ postgresql_root_password }}"
    name: nextcloud
    password: "{{ postgresql_nextcloud_password }}"

- name: Create database user for Nextcloud
  postgresql_db:
    login_host: "{{ postgresql_ip }}"
    login_user: root
    login_password: "{{ postgresql_root_password }}"
    name: "nextcloud"
    owner: "nextcloud"

- name: Create nextcloud container
  docker_container:
    networks:
      - name: dockernet
    image: "nextcloud:stable"
    name: nextcloud
    volumes:
      - "/srv/nextcloud:/var/www/html:rw"
    comparisons:
      env: strict
    env:
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "{{ postgresql_nextcloud_password }}"
      POSTGRES_HOST: "postgres"
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ domain_nextcloud }}"
      REDIS_HOST: "redis"
    restart_policy: "unless-stopped"
  become: yes
